routes/admin.php
<?php

Route::group(['namespace' => 'Admin'], function () {
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', 'HomeController@index')->name('admin.dashboard');
        Route::resource('users', 'userController');
        Route::resource('clients', 'clientController');
        Route::resource('deliveries', 'deliveryController');
        Route::resource('laundries', 'laundryController');
        Route::resource('cities', 'cityController');
        Route::resource('areas', 'areaController');
        Route::resource('neighborhoods', 'neighborhoodController');
        Route::resource('categories', 'categoryController');
        Route::resource('tickets', 'ticketController');
        Route::resource('addresses', 'addressController');
    });
    // // Login
    // Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    // Route::post('login', 'Auth\LoginController@login');
    // Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');

    // // Register
    // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
    // Route::post('register', 'Auth\RegisterController@register');

    // // Passwords
    // Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    // Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    // Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    // Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');

    // Verify
    // Route::get('email/resend', 'Auth\VerificationController@resend')->name('admin.verification.resend');
    // Route::get('email/verify', 'Auth\VerificationController@show')->name('admin.verification.notice');
    // Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('admin.verification.verify');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Traits\CreateApiToken;
use App\Traits\HashPassword;
use App\Traits\HasPhoneCode;

class Client extends Authenticatable
{
    use SoftDeletes, CreateApiToken, HashPassword, HasPhoneCode;

    protected $table = 'clients';
    public $timestamps = true;


    protected $dates = ['deleted_at'];
    protected $fillable = array('name', 'email', 'password', 'image', 'phone', 'verify_mobile', 'mobile_verified', 'balance', 'active', 'fb_token', 'twitter_token', 'google_token', 'is_boot', 'api_token');

    protected $hidden=['password'];
    public function vouchers()
    {
        return $this->hasOne('App\Models\Voucher');
    }

    public function tokens()
    {
        return $this->morphMany('App\Models\Token', 'model');
    }

    public function addresses()
    {
        return $this->hasMany('App\Models\Address', 'client_id');
    }

}

app/Http/Controllers/Admin/clientController.php
<?php

namespace App\Http\Controllers\admin;

use App\Client;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class clientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::all();


        return view('admin.clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:191',
            'email' => 'required|email|max:191|unique:clients,email',
            'password' => 'required|string|confirmed',
            'image' => 'nullable|image',
            'balance' => 'nullable',
            'phone' => 'required|unique:clients,phone',
        ]);
        $requests = $request->except('image');
        if ($request->hasFile('image')) {
            $requests['image'] = saveImage($request->image, 'client');
        }
        Client::create($requests);

        toast('تم الاضافه بنجاح', 'success', 'top-right');
        return redirect()->route('clients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::findOrFail($id);
        return view('admin.clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'name' => 'required|string|max:191',
            'email' => 'required|email|max:191|unique:clients,email',
            'password' => 'required|string|confirmed',
            'image' => 'nullable|image',
            'balance' => 'nullable',
            'phone' => 'required|unique:clients,phone',
            'active'=>'nullable'
        ]);
        $requests = $request->except('image');
        if ($request->hasFile('image')) {
            $requests['image'] = saveImage($request->image, '/client');
        }
        Client::findOrFail($id)->fill($requests)->save();

        toast('تم التعديل بنجاح', 'success', 'top-right');
        return redirect()->route('clients.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Client::destroy($id);
        toast('تم الحذف', 'success', 'top-right');
        return back();
    }

}

app/Http/Controllers/ClientController.php
<?php 

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ClientController extends Controller 
{

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
    
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id)
  {
    
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    
  }
  
}

?>

app/Http/Controllers/api/clients/ApiController.php
<?php

namespace App\Http\Controllers\api\clients;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ApiController extends Controller
{
    //
}

app/Http/Controllers/api/clients/AuthController.php
<?php

namespace App\Http\Controllers\api\clients;

use App\Client;
use App\Models\Token;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{

    public function Register(Request $request)
    {

        $rules = [
            'name' => 'required|string',
            'email' => 'required|email|unique:clients,email',
            'password' => 'required|confirmed',
            'phone' => 'required|numeric|unique:clients,phone',
            'policy'=>'required'
           // 'token' => 'required|string'
        ];


        $validation = validator()->make($request->all(), $rules);

        if ($validation->fails()) {

            return responseJson('0', $validation->errors()->first());

        }
        $requests = $request->except('image');

        DB::beginTransaction();
        $client = Client::create($requests)->load('addresses');
     /*   $token = $client->tokens()->create([
            'token' => $request->token,
            'device' => $request->headers->get('device-type'),
        ]);*/

        //TODO :: add message phone verify

        DB::commit();
        if ($client) {
            $client=Client::with('addresses')->find($client->id);
            return responseJson('1', trans('api.signup.success'), ['client' => $client]);
        } else {
            return responseJson('0', trans('api.signup.error'));

        }
    }

    //--------------------------------------------- Login
    public function Login(Request $request)
    {
        $rules = [
            'email' => 'required',
            'password' => 'required|string',
          //  'token' => 'required|string'
        ];


        $validation = validator()->make($request->all(), $rules);

        if ($validation->fails()) {
            return responseJson('0', $validation->errors()->first());
        }

        $client = Client::with('addresses')->where('email', $request->input('email'))->orWhere('phone', $request->input('email'))->first();



        if (!is_null($client)&&Hash::check($request->password, $client->password)) {


         /*   $token = $client->tokens()->create([
                'token' => $request->token,
                'device' => $request->headers->get('device-type'),
            ]);*/
            return responseJson('1', trans('api.login.success'), ['client' => $client]);


        } else {

            return responseJson('0', trans('api.login.notCorrect'));

        }
    }


    //--------------------------------------------- Show & Edit Student profile
    public function Profile(Request $request)
    {
        $client = Auth::user();

        $rules = [
            'name' => 'nullable',
            'email' => 'nullable|email|unique:clients,email,' . $client->id,
            'password' => 'nullable|confirmed',
            'phone' => 'nullable|numeric|unique:clients,phone,' . $client->id,
            'image' => 'nullable|image',
            'old_password' => 'required_if:password,!=,null',

        ];
        $validation = validator()->make($request->all(), $rules);

        if ($validation->fails()) {

            return responseJson('0', $validation->errors()->first());

        }

        if ($request->has('name') && $request->name != NULL) {
            $client->update($request->only('name'));
        }


        if ($request->has('password') && $request->password != NULL) {


            if (Hash::check($request->old_password, Auth::user()->password)) {
                $client->update(['password' => $request->password]);
            } else {
                return responseJson(0, trans('api.update.password_error'), null);
            }

        }

        if ($request->has('phone') && $request->phone != NULL) {
            $client->update($request->only('phone'));
        }


        if ($request->has('email') && $request->email != NULL) {

            $client->update($request->only('email'));
        }

        

        if ($request->hasFile('image') && $request->image != NULL) {
            $client->update(['image' => saveImage($request->image, '/clients')]);

        }

        $client = Auth::user()->load('addresses');
        return responseJson(1, trans('api.update.success'), ['client' => $client]);

    }




    public function verifyProfile(Request $request)
    {

        $rules =
            [
            'email' => 'required|email|exists:clients,email',
            'verify_mobile' => 'required|exists:clients,verify_mobile',
            ];
        $validation = validator()->make($request->all(), $rules);
        if ($validation->fails()) {
            return responseJson('0', $validation->errors()->first());
        }
        $client = Client::with('addresses')->where('email', $request->email)->where($request->only('verify_mobile'));
        if ($client == null) {
            return responseJson(1, trans('api.update.error'));
        }
        $client->update(['mobile_verified' => Carbon::now()]);
        $client = Client::with('addresses')->where('email', $request->email)->where($request->only('verify_mobile'))->first();
        return responseJson(1, trans('api.update.success'), ['client' => $client]);
    }

    public function resend_verify(Request $request)
    {

        $rules = [
            'email' => 'required|email|exists:clients,email',
        ];
        $validation = validator()->make($request->all(), $rules);
        if ($validation->fails()) {
            return responseJson('0', $validation->errors()->first());
        }
        $client = Client::with('addresses')->where('email', $request->email)->first();
        if ($client == null) {
            return responseJson(1, trans('api.user.resend_code_error'));
        }
        //TODO :: add message phone verify

        return responseJson(0, trans('api.user.resend_code'), $client);
    }

    public function logout(Request $request)
    {
        $rules = [
            'token' => 'required|string|exists:tokens,token,model_id,' . Auth::id()
        ];
        $validation = validator()->make($request->all(), $rules);

        if ($validation->fails()) {
            return responseJson('0', $validation->errors()->first());
        }
        $token = Token::where('token', $request->token)->where('user_id', Auth::id())->delete();

        return responseJson(1, trans('api.logout'));
    }

}

resources/views/admin/clients/_form.blade.php
<div class="m-portlet__body">

    <div class="form-group m-form__group">
        <label for="exampleInputName">الاسم</label>

        {!! Form::text('name',null,['class'=>'form-control m-input','id'=>'exampleInputName','placeholder'=>'ادخل الاسم'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">البريد الالكترونى</label>

        {!! Form::email('email',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'ادخل البريد الالكترونى'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">الهاتف</label>

        {!! Form::text('phone',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'رقم الهاتف'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">الرصيد</label>

        {!! Form::number('balance',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'الرصيد'])!!}
    </div>


    <div class="m-form__group form-group row">
        <label class="col-12 col-form-label">الحساب مفعل</label>
        <div class="col-12">
			<span class="m-switch m-switch--info">
			<label>
                {!! Form::checkbox('active') !!}
                <span></span>
				</label>
				</span>
        </div>

    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputPassword1">كلمه المرور</label>


        {!! Form::password('password',['class'=>'form-control m-input','id'=>'exampleInputPassword1','placeholder'=>'ادخل كلمه المرور'])!!}

    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputPassword2"> تأكيد كلمه المرور </label>

        {!! Form::password('password_confirmation',['class'=>'form-control m-input','id'=>'exampleInputPassword2','placeholder'=>'ادخل تأكيد كلمه المرور'])!!}
    </div>


    <div class="form-group m-form__group">
        @if(isset($user))
            <img src={!!asset($user->image)!!} width="100" height="100">
        @endif
        <label for="imageInput"> الصوره </label>
        <input type="file" class="form-control m-input" name="image" id="imageInput">
    </div>
</div>

resources/views/admin/clients/_table.blade.php
<!--begin: Datatable -->
<table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
    <thead>
    <tr>
        <th>#</th>
        <th>الصوره</th>
        <th>الاسم</th>
        <th>الهاتف</th>
        <th>البريد الالكترونى</th>
        <th>الرصيد</th>
        <th>الاعدادت</th>
    </tr>
    </thead>
    <tbody>
    @foreach($clients as $client)
        <tr>
            <td>{!!$loop->iteration!!}</td>
            <td>
                <img src="{!!asset($client->image)!!}" height="100" width="100" />
            </td>
            <td>{!!$client->name!!}</td>
            <td>{!!$client->phone!!}</td>
            <td>{!!$client->email!!}</td>
            <td>{!!$client->balane!!}</td>
            <td>
                <a href="{!!route('clients.edit',$client->id)!!}" class="btn btn-primary">
                    <i class="fas fa-pen"></i>
                    تعديل</a>

                <form method="POST" action="{!!route('clients.destroy',$client->id)!!}">
                    @csrf()
                     @method('delete')
                    <button type="submit" class="btn btn-danger">
                        <i class="fas fa-trash"></i>
                        حذف
                    </button>
                </form>
            </td>
        </tr>


    @endforeach

    </tbody>

</table>

resources/views/admin/clients/create.blade.php
@extends('admin.layouts.app')
@section('title') اضافه عميل@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['العملاء'=>route('clients.index'),'اضافه'=>route('clients.create')])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')


<div class="m-content">
    <div class="row">
        <div class="col-md-12">

            <!--begin::Portlet-->
            <div class="m-portlet m-portlet--tab">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                اضافه عميل
                            </h3>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->

                {!! Form::open(['method'=>'post','route'=>'clients.store','files'=>'true','class'=>'m-form m-form--fit
                m-form--label-align-right'])!!}
                @include('admin.clients._form')

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </div>
                </div>

                {!!Form::close()!!}
                <!--end::Form-->
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')@endsection

resources/views/admin/clients/edit.blade.php
@extends('admin.layouts.app')
@section('title') تعديل بيانات {!!$client->name!!}@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['العملاء'=>route('clients.index'),'تعديل'=>route('clients.edit',$client->id)])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')


<div class="m-content">
    <div class="row">
        <div class="col-md-12">

            <!--begin::Portlet-->
            <div class="m-portlet m-portlet--tab">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                تعديل {!! $client->name!!}
                            </h3>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->

                {!! Form::model($client,['method'=>'put','route'=>['clients.update',$client->id],'files'=>'true','class'=>'m-form m-form--fit
                m-form--label-align-right'])!!}
                @include('admin.clients._form')

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </div>
                </div>
                {!!Form::close()!!}
                <!--end::Form-->
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')@endsection

resources/views/admin/clients/index.blade.php
@extends('admin.layouts.app')
@section('title') العملاء@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['العملاء'=>route('clients.index'),])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')

 <div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    كل العملاء
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{!!route('clients.create')!!}" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air">
                        <span>
                            <i class="la la-cart-plus"></i>
                            <span>اضافه عميل</span>
                        </span>
                    </a>
                </li>
                <li class="m-portlet__nav-item"></li>

            </ul>
        </div>
    </div>
    <div class="m-portlet__body">

     @include('admin.clients._table')
    </div>
</div>

 @endsection
@section('scripts')@endsection

resources/views/admin/clients/show.blade.php
@extends('admin.layouts.app')
@section('title')@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['الاعضاء'=>'/users','اضافه'=>'/users/create'])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')@endsection
@section('scripts')@endsection