routes/admin.php
<?php

Route::group(['namespace' => 'Admin'], function () {
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', 'HomeController@index')->name('admin.dashboard');
        Route::resource('users', 'userController');
        Route::resource('clients', 'clientController');
        Route::resource('deliveries', 'deliveryController');
        Route::resource('laundries', 'laundryController');
        Route::resource('cities', 'cityController');
        Route::resource('areas', 'areaController');
        Route::resource('neighborhoods', 'neighborhoodController');
        Route::resource('categories', 'categoryController');
        Route::resource('tickets', 'ticketController');
        Route::resource('addresses', 'addressController');
    });
    // // Login
    // Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    // Route::post('login', 'Auth\LoginController@login');
    // Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');

    // // Register
    // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
    // Route::post('register', 'Auth\RegisterController@register');

    // // Passwords
    // Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    // Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    // Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    // Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');

    // Verify
    // Route::get('email/resend', 'Auth\VerificationController@resend')->name('admin.verification.resend');
    // Route::get('email/verify', 'Auth\VerificationController@show')->name('admin.verification.notice');
    // Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('admin.verification.verify');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $fillable=['ticket_number','title', 'ticked_number', 'model_type', 'model_id', 'priority', 'status', 'has_new_message'];


    public function client(){

        return $this->morphTo('model');
    }

    public function messages()
    {

        return $this->hasMany('App\Models\TicketMessage','ticket_id');

    }
}

app/Http/Controllers/Admin/ticketController.php
<?php

namespace App\Http\Controllers\admin;

use App\Client;
use App\Delivery;
use App\Http\Controllers\Controller;
use App\Laundry;
use App\Models\Ticket;
use Illuminate\Http\Request;

class ticketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tickets = Ticket::all();
        return view('admin.tickets.index', compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::all();
        $laundries = Laundry::all();
        $deliveries = Delivery::all();

        return view('admin.tickets.create', compact('clients', 'laundries', 'deliveries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            "title" => "required|string",
            "priority" => "required|string|in:low,normal,high",
            "status" => "required|string|in:open,closed",
            "model_type" => "required|string|in:App\Client,App\Delivery,App\Laundry",
            "model_id" => "required|integer",
            "message" => "required|string",
            "file" => "nullable",
        ]);
        $ticket_data = $request->except('message', 'file');
        $ticket_data['ticket_number'] = rand(000000, 999999);
        $message_data = [
            'message' => $request->message,
            'replier_type' => $request->model_type,
            'replier_id' => $request->model_id,
        ];
        if ($request->hasFile('file')) {
            $messag_data['file'] = saveImage($request->file('file'), 'tickets');
        }
        $ticket = Ticket::create($ticket_data);
        $ticket->messages()->create($message_data);
        toast('تم الاضافه بنجاح', 'success', 'top-right');

        return redirect()->route('tickets.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ticket $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(ticket $ticket)
    {
        dd($ticket);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ticket $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ticket = Ticket::findOrFail($id);
        $clients = Client::all();
        $laundries = Laundry::all();
        $deliveries = Delivery::all();


        return view('admin.tickets.edit', compact('ticket', 'clients', 'laundries', 'deliveries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\ticket $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [
            "title" => "required|string",
            "priority" => "required|string|in:low,normal,high",
            "status" => "required|string|in:open,closed",
            "model_type" => "required|string|in:App\Client,App\Delivery,App\Laundry",
            "model_id" => "required|integer",
            "message" => "nullable",
            "file" => "nullable",
        ]);
        $ticket = Ticket::findOrFail($id);
        $ticket_data = $request->except('message', 'file');
        $ticket_data['ticket_number'] = rand(000000, 999999);
        $message_data = [
            'message' => $request->message,
            'replier_type' => $request->model_type,
            'replier_id' => $request->model_id,
        ];
        if ($request->hasFile('file')) {
            $messag_data['file'] = saveImage($request->file('file'), 'tickets');
        }
        $ticket->fill($ticket_data);
        $ticket->messages()->create($message_data);
        $ticket->save();
        toast('تم الاضافه بنجاح', 'success', 'top-right');
        return redirect()->route('tickets.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ticket $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Ticket::destroy($id);
        toast('تم الحذف بنجاح', 'success', 'top-right');

        return back();
    }
}

resources/views/admin/tickets/_form.blade.php
<div class="m-portlet__body">

    <div class="form-group m-form__group">
        <label for="exampleInputName">الموضوع</label>

        {!! Form::text('title',null,['class'=>'form-control m-input','id'=>'exampleInputName','placeholder'=>'ادخل الموضوع'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">الاهميه</label>

        {!! Form::select('priority',['low'=>'low','normal'=>'normal','important'=>'important'],null,['class'=>'form-control m-input select2','id'=>'exampleInputEmail1','placeholder'=>' الاهميه'])!!}
    </div>
    <div class="form-group m-form__group">
        <label for="exampleInpu">الحاله</label>

        {!! Form::select('status',['closed'=>'مغلقه','open'=>'مفتوحه'],null,['class'=>'form-control m-input select2','id'=>'exampleInpu','placeholder'=>'ادخل الحاله'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampl">نوع العضويه</label>

        {!! Form::select('model_type',['App\Client'=>'عميل','App\laundry'=>'مغسله','App\Delivery'=>'مندوب'],null,['class'=>'form-control m-input select2','id'=>'exampl','placeholder'=>'نوع العضويه','onChange'=>'getClientByType(this.value)'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exa">العضو</label>

        {!! Form::select('model_id',
        (isset($ticket))?$ticket->model_type::get()->pluck('name','id'):[]
        ,null,['class'=>'form-control m-input select2','id'=>'exa','placeholder'=>'ادخل العضو'])!!}
    </div>
@if(!isset($ticket))
    <div class="form-group m-form__group">
        <label>الرساله</label>

        {!! Form::textarea('message',null,['class'=>'form-control m-input ','placeholder'=>'ادخل العضو'])!!}
    </div>
    <div class="form-group m-form__group">
        <label>الرساله</label>

        {!! Form::file('file',null,['class'=>'form-control m-input ','placeholder'=>'ادخل العضو'])!!}
    </div>
    @else
    @foreach($ticket->messages as $message)
<h3>الرسائل السابقه </h3>
        <hr>
            <div class="form-group m-form__group">
                <label>الرساله</label>
<textarea disabled="" class="form-control">{!! $message->message !!}</textarea>
            </div>
        @if($message->file)
            <div class="form-group m-form__group">
                <label>الملفات المرفقه</label>
<a href="{!! asset($message->file) !!}" download=""> <i class="fas fa-cloud-download"></i></a>
            </div>
            @endif

        @endforeach


    <h3>اضافه رساله جديده</h3>

        <div class="form-group m-form__group">
            <label>الرساله</label>

            {!! Form::textarea('message',null,['class'=>'form-control m-input ','placeholder'=>'ادخل العضو'])!!}
        </div>
        <div class="form-group m-form__group">
            <label>الرساله</label>

            {!! Form::file('file',null,['class'=>'form-control m-input ','placeholder'=>'ادخل العضو'])!!}
        </div>
    @endif

</div>

@push('scripts')

    <script>

        var types = {
            "App\\Client":{!! $clients->pluck('name','id') !!},
            'App\\laundry': {!! $laundries->pluck('name','id') !!},
            'App\\Delivery':   {!! $deliveries->pluck('name','id') !!}
        };

    </script>

@endpush

resources/views/admin/tickets/_table.blade.php
<!--begin: Datatable -->
<table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
    <thead>
    <tr>
        <th>التسلسل</th>
        <th>العنوان</th>
        <th>العضو</th>
        <th>الحاله</th>
        <th>الاهميه</th>
        <th>صاحب التذكره</th>
        <th>التاريخ</th>
        <th>اخر رساله</th>
        <th>الاعدادت</th>
    </tr>
    </thead>
    <tbody>
    @foreach($tickets as $ticket)
        <tr>
            <td>{!!$loop->iteration!!}</td>
            <td>{!!$ticket->title!!}</td>
            <td>{!!optional($ticket->client)->name!!}</td>
            <td>{!!$ticket->status!!}</td>
            <td>{!!$ticket->priority!!}</td>
            <td>{!!optional($ticket->client)->name!!}</td>
            <td>{!!optional($ticket->created_at)->format('Y-m-d')!!}</td>
            <td>{!!optional(optional($ticket->messages)->last())->message!!}</td>
            <td>
                <a href="{!!route('tickets.edit',$ticket->id)!!}" class="btn btn-primary">
                    <i class="fas fa-pen"></i>
                    تعديل</a>

                <form method="POST" action="{!!route('tickets.destroy',$ticket->id)!!}">
                    @csrf()
                     @method('delete')
                    <button type="submit" class="btn btn-danger">
                        <i class="fas fa-trash"></i>
                        حذف
                    </button>
                </form>
            </td>
        </tr>


    @endforeach

    </tbody>

</table>

resources/views/admin/tickets/create.blade.php
@extends('admin.layouts.app')
@section('title') اضافه تذكره@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['تذكره'=>route('tickets.index'),'اضافه'=>route('tickets.create')])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')


<div class="m-content">
    <div class="row">
        <div class="col-md-12">

            <!--begin::Portlet-->
            <div class="m-portlet m-portlet--tab">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                اضافه تذكره
                            </h3>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->

                {!! Form::open(['method'=>'post','route'=>'tickets.store','files'=>'true','class'=>'m-form m-form--fit
                m-form--label-align-right'])!!}
                @include('admin.tickets._form')

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </div>
                </div>

                {!!Form::close()!!}
                <!--end::Form-->
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')@endsection

resources/views/admin/tickets/edit.blade.php
@extends('admin.layouts.app')
@section('title') تعديل بيانات {!!$ticket->name!!}@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['التذاكر'=>route('tickets.index'),'تعديل'=>route('tickets.edit',$ticket->id)])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')


<div class="m-content">
    <div class="row">
        <div class="col-md-12">

            <!--begin::Portlet-->
            <div class="m-portlet m-portlet--tab">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                 تعديل   {!! $ticket->name!!}
                            </h3>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->

                {!! Form::model($ticket,['method'=>'put','route'=>['tickets.update',$ticket->id],'files'=>'true','class'=>'m-form m-form--fit
                m-form--label-align-right'])!!}
                @include('admin.tickets._form')

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </div>
                </div>
                {!!Form::close()!!}
                <!--end::Form-->
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')@endsection

resources/views/admin/tickets/index.blade.php
@extends('admin.layouts.app')
@section('title') التذاكر@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['التذاكر'=>route('tickets.index'),])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')

 <div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    كل التذاكر
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{!!route('tickets.create')!!}" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air">
                        <span>
                            <i class="la la-cart-plus"></i>
                            <span>اضافه تذكره</span>
                        </span>
                    </a>
                </li>
                <li class="m-portlet__nav-item"></li>

            </ul>
        </div>
    </div>
    <div class="m-portlet__body">

     @include('admin.tickets._table')
    </div>
</div>

 @endsection
@section('scripts')@endsection

resources/views/admin/tickets/show.blade.php
@extends('admin.layouts.app')
@section('title')@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['الاعضاء'=>'/users','اضافه'=>'/users/create'])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')@endsection
@section('scripts')@endsection