routes/admin.php
<?php

Route::group(['namespace' => 'Admin'], function () {
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', 'HomeController@index')->name('admin.dashboard');
        Route::resource('users', 'userController');
        Route::resource('clients', 'clientController');
        Route::resource('deliveries', 'deliveryController');
        Route::resource('laundries', 'laundryController');
        Route::resource('cities', 'cityController');
        Route::resource('areas', 'areaController');
        Route::resource('neighborhoods', 'neighborhoodController');
        Route::resource('categories', 'categoryController');
        Route::resource('tickets', 'ticketController');
        Route::resource('addresses', 'addressController');
    });
    // // Login
    // Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    // Route::post('login', 'Auth\LoginController@login');
    // Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');

    // // Register
    // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
    // Route::post('register', 'Auth\RegisterController@register');

    // // Passwords
    // Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    // Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    // Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    // Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');

    // Verify
    // Route::get('email/resend', 'Auth\VerificationController@resend')->name('admin.verification.resend');
    // Route::get('email/verify', 'Auth\VerificationController@show')->name('admin.verification.notice');
    // Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('admin.verification.verify');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/laundryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Laundry;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class laundryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $laundries = Laundry::all();


        return view('admin.laundries.index', compact('laundries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.laundries.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       /* $this->validate($request, [
            'name' => 'required|string|max:191',
            'email' => 'required|email|max:191|unique:laundries,email',
            'password' => 'required|string|confirmed',
            'image' => 'nullable|image',
            'balance' => 'nullable',
            'phone' => 'required|unique:laundries,phone',
            'salary' => 'nullable',
            'percent' => 'nullable'

        ]);*/
        $requests = $request->except('image');
        if ($request->hasFile('image')) {
            $requests['image'] = saveImage($request->image, 'laundry');
        }
        Laundry::create($requests);

        toast('تم الاضافه بنجاح', 'success', 'top-right');
        return redirect()->route('laundries.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $laundry = Laundry::findOrFail($id);

        return view('admin.laundries.edit', compact('laundry'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

       /* $this->validate($request, [
            'name' => 'required|string|max:191',
            'email' => 'required|email|max:191|unique:laundries,email',
            'password' => 'required|string|confirmed',
            'image' => 'nullable|image',
            'balance' => 'nullable',
            'phone' => 'required|unique:laundries,phone',
            'salary' => 'nullable',
            'percent' => 'nullable'

        ]);*/
        $requests = $request->except('image');
        if ($request->hasFile('image')) {
            $requests['image'] = saveImage($request->image, '/laundry');
        }
        Laundry::findOrFail($id)->fill($requests)->save();
        toast('تم التعديل بنجاح', 'success', 'top-right');
        return redirect()->route('laundries.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Laundry::destroy($id);
        toast('تم الحذف', 'success', 'top-right');
        return back();
    }

}

app/Http/Controllers/LaundryController.php
<?php 

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LaundryController extends Controller 
{

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
    
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id)
  {
    
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    
  }
  
}

?>

app/Http/Controllers/api/laundries/ApiController.php
<?php

namespace App\Http\Controllers\api\laundries;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ApiController extends Controller
{
    //
}

app/Http/Controllers/api/laundries/AuthController.php
<?php

namespace App\Http\Controllers\api\laundries;

use App\Laundry;
use App\Models\Token;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{
    public function Register(Request $request)
    {

        $rules = [
            'name' => 'required|string',
            'email' => 'required|email|unique:laundries,email',
            'password' => 'required|confirmed',
            'phone' => 'required|numeric|unique:laundries,phone',
            'policy' => 'required',
            'Commercial_number' => 'required|string',
            'address' => 'required|string',

        ];

        /*

        */
        $validation = validator()->make($request->all(), $rules);

        if ($validation->fails()) {

            return responseJson('0', $validation->errors()->first());

        }
        $requests = $request->except('image');

        DB::beginTransaction();
        $laundry = Laundry::create($requests);
        /*   $token = $laundry->tokens()->create([
               'token' => $request->token,
               'device' => $request->headers->get('device-type'),
           ]);*/

        //TODO :: add message phone verify

        DB::commit();
        if ($laundry) {
            $laundry = Laundry::find($laundry->id);
            return responseJson('1', trans('api.signup.success'), ['laundry' => $laundry]);
        } else {
            return responseJson('0', trans('api.signup.error'));

        }
    }

    //--------------------------------------------- Login
    public function Login(Request $request)
    {
        $rules = [
            'email' => 'required',
            'password' => 'required|string',
            //  'token' => 'required|string'
        ];


        $validation = validator()->make($request->all(), $rules);

        if ($validation->fails()) {
            return responseJson('0', $validation->errors()->first());
        }

        $laundry = Laundry::where('email', $request->input('email'))->orWhere('phone', $request->input('email'))->first();


        if (!is_null($laundry) && Hash::check($request->password, $laundry->password)) {

            if ($laundry->active) {

                return responseJson('1', trans('api.login.success'), ['laundry' => $laundry]);
            } else {

                return responseJson('0', trans('api.login.account_not_active'));
            }


        } else {

            return responseJson('0', trans('api.login.notCorrect'));

        }
    }


    //--------------------------------------------- Show & Edit Student profile
    public function Profile(Request $request)
    {
        $laundry = Auth::user();

        $rules = [
            'name' => 'nullable',
            'email' => 'nullable|email|unique:laundries,email,' . $laundry->id,
            'password' => 'nullable|confirmed',
            'phone' => 'nullable|numeric|unique:laundries,phone,' . $laundry->id,
            'image' => 'nullable|image',
            'old_password' => 'required_if:password,!=,null',
            'Commercial_number' => 'nullable|unique:laundries,Commercial_number,' . $laundry->id,
            'address' => 'nullable',
            'clothes' => 'nullable',
            'carpets' => 'nullable',
            'mattresses' => 'nullable',
            'lat' => 'nullable',
            'lng' => 'nullable',
            'clean' => 'nullable',
            'dry_clean' => 'nullable',
            'clean_ironing' => 'nullable',
            'Commercial_cert' => 'nullable|image',
            'laundry_personal_id' => 'nullable|image',
            'shop_personal_id' => 'nullable|image',
        ];
        $validation = validator()->make($request->all(), $rules);

        if ($validation->fails()) {

            return responseJson('0', $validation->errors()->first());

        }

        if ($request->has('name') && $request->name != NULL) {
            $laundry->update($request->only('name'));
        }


        if ($request->has('password') && $request->password != NULL) {


            if (Hash::check($request->old_password, Auth::user()->password)) {
                $laundry->update(['password' => $request->password]);
            } else {
                return responseJson(0, trans('api.update.password_error'), null);
            }

        }

        if ($request->has('phone') && $request->phone != NULL) {
            $laundry->update($request->only('phone'));
        }


        if ($request->has('email') && $request->email != NULL) {

            $laundry->update($request->only('email'));
        }

        /*
=
            'clean_ironing'=>'nullable',*/
        if ($request->has('dry_clean') && $request->dry_clean != NULL) {

            $laundry->update($request->only('dry_clean'));
        }
        if ($request->has('clean_ironing') && $request->clean_ironing != NULL) {

            $laundry->update($request->only('clean_ironing'));
        }

        if ($request->has('clean') && $request->clean != NULL) {

            $laundry->update($request->only('clean'));
        }

        if ($request->has('lat') && $request->lat != NULL) {

            $laundry->update($request->only('lat'));
        }

        if ($request->has('lng') && $request->lng != NULL) {

            $laundry->update($request->only('lng'));
        }
        if ($request->has('mattresses') && $request->mattresses != NULL) {

            $laundry->update($request->only('mattresses'));
        }

        if ($request->has('carpets') && $request->carpets != NULL) {

            $laundry->update($request->only('carpets'));

        }
        if ($request->has('clothes') && $request->clothes != NULL) {

            $laundry->update($request->only('clothes'));

        }

        if ($request->has('Commercial_number') && $request->Commercial_number != NULL) {

            $laundry->update($request->only('Commercial_number'));
        }
        if ($request->has('address') && $request->address != NULL) {

            $laundry->update($request->only('address'));
        }
        if ($request->has('clothes') && $request->clothes != NULL) {

            $laundry->update($request->only('clothes'));
        }


        if ($request->hasFile('image') && $request->image != NULL) {
            $laundry->update(['image' => saveImage($request->image, '/laundries')]);

        }
        if ($request->hasFile('Commercial_cert') && $request->Commercial_cert != NULL) {
            $laundry->update(['Commercial_cert' => saveImage($request->Commercial_cert, '/laundries')]);

        }
        if ($request->hasFile('laundry_personal_id') && $request->laundry_personal_id != NULL) {
            $laundry->update(['laundry_personal_id' => saveImage($request->laundry_personal_id, '/laundries')]);
        }
        if ($request->hasFile('shop_personal_id') && $request->shop_personal_id != NULL) {
            $laundry->update(['shop_personal_id' => saveImage($request->shop_personal_id, '/laundries')]);
        }


        $laundry = Auth::user();
        return responseJson(1, trans('api.update.success'), ['laundry' => $laundry]);
    }


    public function verifyProfile(Request $request)
    {

        $rules =
            [
                'email' => 'required|email|exists:laundries,email',
                'verify_mobile' => 'required|exists:laundries,verify_mobile',
            ];
        $validation = validator()->make($request->all(), $rules);
        if ($validation->fails()) {
            return responseJson('0', $validation->errors()->first());
        }
        $laundry = Laundry::with('addresses')->where('email', $request->email)->where($request->only('verify_mobile'));
        if ($laundry == null) {
            return responseJson(1, trans('api.update.error'));
        }
        $laundry->update(['mobile_verified' => Carbon::now()]);
        $laundry = Laundry::where('email', $request->email)->where($request->only('verify_mobile'))->first();
        return responseJson(1, trans('api.update.success'), ['laundry' => $laundry]);
    }

    public function resend_verify(Request $request)
    {

        $rules = [
            'email' => 'required|email|exists:laundries,email',
        ];
        $validation = validator()->make($request->all(), $rules);
        if ($validation->fails()) {
            return responseJson('0', $validation->errors()->first());
        }
        $laundry = Laundry::where('email', $request->email)->first();
        if ($laundry == null) {
            return responseJson(1, trans('api.user.resend_code_error'));
        }
        //TODO :: add message phone verify

        return responseJson(0, trans('api.user.resend_code'), $laundry);
    }

    public function logout(Request $request)
    {
        $rules = [
            'token' => 'required|string|exists:tokens,token,model_id,' . Auth::id()
        ];
        $validation = validator()->make($request->all(), $rules);

        if ($validation->fails()) {
            return responseJson('0', $validation->errors()->first());
        }
        $token = Token::where('token', $request->token)->where('user_id', Auth::id())->delete();

        return responseJson(1, trans('api.logout'));
    }
}

resources/views/admin/laundries/_form.blade.php
<div class="m-portlet__body">

    {{--'Commercial_number', 'address', 'clothes', 'carpets', 'lat', 'lng', 'neighborhood_id', 'clean', 'dry_clean', 'clean_ironing',--}}
    <div class="form-group m-form__group">
        <label for="exampleInputName">الاسم</label>

        {!! Form::text('name',null,['class'=>'form-control m-input','id'=>'exampleInputName','placeholder'=>'ادخل الاسم'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">البريد الالكترونى</label>

        {!! Form::email('email',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'ادخل البريد الالكترونى'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">الهاتف</label>

        {!! Form::text('phone',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'رقم الهاتف'])!!}
    </div>
    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">رقم السجل</label>

        {!! Form::text('Commercial_number',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'رقم السجل'])!!}
    </div>
    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">العنوان</label>

        {!! Form::text('address',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'العنوان'])!!}
    </div>


    <div class="form-group m-form__group">
        <label for="exampleInputPassword1">كلمه المرور</label>


        {!! Form::password('password',['class'=>'form-control m-input','id'=>'exampleInputPassword1','placeholder'=>'ادخل كلمه المرور'])!!}

    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputPassword2"> تأكيد كلمه المرور </label>

        {!! Form::password('password_confirmation',['class'=>'form-control m-input','id'=>'exampleInputPassword2','placeholder'=>'ادخل تأكيد كلمه المرور'])!!}
    </div>


    <div class="m-form__group form-group row">
        <label class="col-12 col-form-label">انواع القماش</label>
        <div class="col-4">
			<span class="m-switch m-switch--info">
			<label>
                {!! Form::checkbox('clothes') !!}
                <span></span>ملابس
				</label>
				</span>
        </div>
        <div class="col-4">
			<span class="m-switch m-switch--info">
			<label>
                {!! Form::checkbox('carpets') !!}
                <span></span>سجاد
				</label>
			</span>
        </div>
   <div class="col-4">
			<span class="m-switch m-switch--info">
			<label>
                {!! Form::checkbox('mattresses') !!}
                <span></span>مفارش
				</label>
			</span>
        </div>

    </div>
    <div class="m-form__group form-group row">
        <label class="col-12 col-form-label">انواع الغسيل</label>
        <div class="col-4">
			<span class="m-switch m-switch--info">
			<label>
                {!! Form::checkbox('clean') !!}
                <span></span>غسيل
				</label>
				</span>
        </div>
        <div class="col-4">
			<span class="m-switch m-switch--info">
			<label>
                {!! Form::checkbox('dry_clean') !!}
                <span></span>غسيل جاف
				</label>
				</span>
        </div>
        <div class="col-4">
			<span class="m-switch m-switch--info">
			<label>
                {!! Form::checkbox('clean_ironing') !!}
                <span> </span>غسيل  ومكوي
				</label>
				</span>
        </div>

    </div>

    <div class="form-group m-form__group">
        @if(isset($user))
            <img src={!!asset($user->image)!!} width="100" height="100">
        @endif
        <label for="imageInput"> الصوره </label>
        <input type="file" class="form-control m-input" name="image" id="imageInput">
    </div>
</div>

{!! Form::hidden('lat',null)!!}
{!! Form::hidden('lng',null)!!}
<div id='map' style="width: 100%; height: 500px;"></div>
</div>
@if(isset($laundry))
    <script>
        var lat={!! $laundry->lat !!}
        var lng={!! $laundry->lat !!}


    </script>

@endif

resources/views/admin/laundries/_table.blade.php
<!--begin: Datatable -->
<table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
    <thead>
    <tr>


        <th>#</th>
        <th>الصوره</th>
        <th>الاسم</th>
        <th>الهاتف</th>
        <th>البريد الالكترونى</th>
        <th>رقم السجل</th>
        <th>العنوان</th>
        <th>انواع الملابس</th>
        <th>المنطقه</th>
        <th>انواع الغسيل</th>
        <th>الاعدادت</th>
    </tr>
    </thead>
    <tbody>
    @foreach($laundries as $laundry)
        <tr>
            <td>{!!$loop->iteration!!}</td>
            <td><img src="{!!asset($laundry->image)!!}" height="100" width="100" /> </td>
            <td>{!!$laundry->name!!}</td>
            <td>{!!$laundry->phone!!}</td>
            <td>{!!$laundry->email!!}</td>
            <td>{!!$laundry->Commercial_number!!}</td>
            <td>{!!$laundry->address!!}</td>
            <td>
                <ul>
                @if($laundry->clothes==1)<li>    ملابس </li>@endif
                @if($laundry->carpets==1)<li>    سجاد </li>@endif
                </ul>
            </td>
            <td>{!! optional($laundry->neighborhood)->name_ar !!}</td>
            <td>
                <ul>
                    @if($laundry->clean==1)<li>    غسيل </li>@endif
                    @if($laundry->dry_clean==1)<li>    غسيل جاف </li>@endif
                    @if($laundry->clean_ironing==1)<li>    غسيل و كوى </li>@endif
                </ul>
            </td>
=            <td>
                <a href="{!!route('laundries.edit',$laundry->id)!!}" class="btn btn-primary">
                    <i class="fas fa-pen"></i>
                    تعديل</a>

                <form method="POST" action="{!!route('laundries.destroy',$laundry->id)!!}">
                    @csrf()
                     @method('delete')
                    <button type="submit" class="btn btn-danger">
                        <i class="fas fa-trash"></i>
                        حذف
                    </button>
                </form>
            </td>

        </tr>
    @endforeach
    </tbody>

</table>

resources/views/admin/laundries/create.blade.php
@extends('admin.layouts.app')
@section('title') اضافه مغسله@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['المغاسل'=>route('laundries.index'),'اضافه'=>route('users.create')])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')


<div class="m-content">
    <div class="row">
        <div class="col-md-12">

            <!--begin::Portlet-->
            <div class="m-portlet m-portlet--tab">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                اضافه مغسله
                            </h3>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->

                {!! Form::open(['method'=>'post','route'=>'laundries.store','files'=>'true','class'=>'m-form m-form--fit
                m-form--label-align-right'])!!}
                @include('admin.laundries._form')

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </div>
                </div>

                {!!Form::close()!!}
                <!--end::Form-->
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')@endsection

resources/views/admin/laundries/edit.blade.php
@extends('admin.layouts.app')
@section('title') تعديل بيانات {!!$laundry->name!!}@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['المديرين'=>route('laundries.index'),'تعديل'=>route('laundries.edit',$laundry->id)])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')


<div class="m-content">
    <div class="row">
        <div class="col-md-12">

            <!--begin::Portlet-->
            <div class="m-portlet m-portlet--tab">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                تعديل {!! $laundry->name!!}
                            </h3>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->

                {!! Form::model($laundry,['method'=>'put','route'=>['laundries.update',$laundry->id],'files'=>'true','class'=>'m-form m-form--fit
                m-form--label-align-right'])!!}
                @include('admin.laundries._form')

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </div>
                </div>

                {!!Form::close()!!}
                <!--end::Form-->
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')@endsection

resources/views/admin/laundries/index.blade.php
@extends('admin.layouts.app')
@section('title') المغاسل@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['المغاسل'=>route('laundries.index'),])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')

 <div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    كل المغاسل
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{!!route('laundries.create')!!}" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air">
                        <span>
                            <i class="la la-cart-plus"></i>
                            <span>اضافه المغاسل</span>
                        </span>
                    </a>
                </li>
                <li class="m-portlet__nav-item"></li>

            </ul>
        </div>
    </div>
    <div class="m-portlet__body">

     @include('admin.laundries._table')
    </div>
</div>

 @endsection
@section('scripts')@endsection

resources/views/admin/laundries/show.blade.php
@extends('admin.layouts.app')
@section('title')@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['الاعضاء'=>'/users','اضافه'=>'/users/create'])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')@endsection
@section('scripts')@endsection