routes/admin.php
<?php

Route::group(['namespace' => 'Admin'], function () {
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', 'HomeController@index')->name('admin.dashboard');
        Route::resource('users', 'userController');
        Route::resource('clients', 'clientController');
        Route::resource('deliveries', 'deliveryController');
        Route::resource('laundries', 'laundryController');
        Route::resource('cities', 'cityController');
        Route::resource('areas', 'areaController');
        Route::resource('neighborhoods', 'neighborhoodController');
        Route::resource('categories', 'categoryController');
        Route::resource('tickets', 'ticketController');
        Route::resource('addresses', 'addressController');
    });
    // // Login
    // Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    // Route::post('login', 'Auth\LoginController@login');
    // Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');

    // // Register
    // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
    // Route::post('register', 'Auth\RegisterController@register');

    // // Passwords
    // Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    // Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    // Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    // Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');

    // Verify
    // Route::get('email/resend', 'Auth\VerificationController@resend')->name('admin.verification.resend');
    // Route::get('email/verify', 'Auth\VerificationController@show')->name('admin.verification.notice');
    // Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('admin.verification.verify');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model 
{

    protected $table = 'categories';
    public $timestamps = true;

    use SoftDeletes;

    protected $dates = ['deleted_at'];
    protected $fillable = array( 'name_ar', 'name_en', 'image', 'type', 'clean_price', 'dry_clean_price', 'clean_ironing_price', 'fast_clean_price', 'fast_dry_clean_price', 'fast_clean_ironing_price');
    protected $hidden = array('name_ar');

}

app/Http/Controllers/Admin/categoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class categoryController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $categories = Category::all();


        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name_ar' => 'required|string|max:191,unique:categories,name_ar',
            'name_en' => 'required|string|max:191,unique:categories,name_en',
            'image' => 'required|image',
            'type' => 'required|string|in:clothes,carpets,mattresses',
            'clean_price' => 'required|numeric',
            'dry_clean_price' => 'required|numeric',
            'clean_ironing_price' => 'required|numeric',
            'fast_clean_price'=>'required_if:type,clothes',
            'fast_dry_clean_price'=>'required_if:type,clothes',
            'fast_clean_ironing_price'=>'required_if:type,clothes'

        ]);
        $requests = $request->except('image');
        $requests['image']=saveImage($request->image,'categories');
        Category::create($requests);

        toast('تم الاضافه بنجاح', 'success', 'top-right');
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'name_ar' => 'required|string|max:191,unique:categories,name_ar',
            'name_en' => 'required|string|max:191,unique:categories,name_en',
            'image' => 'nullable|image',
            'type' => 'required|string|in:clothes,carpets,mattresses',
            'clean_price' => 'required|numeric',
            'dry_clean_price' => 'required|numeric',
            'clean_ironing_price' => 'required|numeric',
            'fast_clean_price'=>'required_if:type,clothes',
            'fast_dry_clean_price'=>'required_if:type,clothes',
            'fast_clean_ironing_price'=>'required_if:type,clothes'

        ]);
        $requests = $request->except('image');
        if($request->has('image')){
        $requests['image']=saveImage($request->image,'categories');
        }
        Category::findOrFail($id)->fill($requests)->save();

        toast('تم التعديل بنجاح', 'success', 'top-right');
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::destroy($id);
        toast('تم الحذف', 'success', 'top-right');
        return back();
    }
}

app/Http/Controllers/CategoryController.php
<?php 

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller 
{

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
    
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id)
  {
    
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    
  }
  
}

?>

resources/views/admin/categories/_form.blade.php
<div class="m-portlet__body">
    {{--'name_ar', 'name_en', 'image', 'type', 'clean_price', 'dry_clean_price', 'clean_ironing_price', 'fast_clean_price', 'fast_dry_clean_price', 'fast_clean_ironing_price'--}}
    <div class="form-group m-form__group">
        <label for="exampleInputName">الاسم بالعربيه</label>

        {!! Form::text('name_ar',null,['class'=>'form-control m-input','id'=>'exampleInputName','placeholder'=>'ادخل الاسم بالعربيه'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">ادخل الاسم بالانجليزيه</label>
        {!! Form::text('name_en',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'ادخل الاسم بالانجليزيه'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">النوع</label>
        {!! Form::select('type',['clothes'=>'ملابس','carpets'=>'سجاد','mattresses'=>'مفارش'],null,['class'=>'form-control m-input select2','id'=>'exampleInputEmail1','placeholder'=>'النوع','onchange'=>'toggleFastOrder(this.value)'])!!}
    </div>


    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">سعر الغسيل</label>
        {!! Form::number('clean_price',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'سعر الغسيل'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">سعر الغسيل الجاف</label>
        {!! Form::number('dry_clean_price',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'سعر الغسيل الجاف'])!!}
    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">سعر الغسيل والكى</label>
        {!! Form::number('clean_ironing_price',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'سعر الغسيل والكى'])!!}
    </div>

    <div class="fastOrder @if(isset($category)&&$category->type=='clothes') d-block @else d-none @endif"
    >
        <div class="form-group m-form__group">
            <label for="exampleInputEmail1">سعر الغسيل سريع</label>
            {!! Form::number('fast_clean_price',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'سعر الغسيل'])!!}
        </div>

        <div class="form-group m-form__group">
            <label for="exampleInputEmail1">سعر الغسيل الجاف سريع</label>
            {!! Form::number('fast_dry_clean_price',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'سعر الغسيل الجاف'])!!}
        </div>

        <div class="form-group m-form__group">
            <label for="exampleInputEmail1">سعر الغسيل والكى سريع</label>
            {!! Form::number('fast_clean_ironing_price',null,['class'=>'form-control m-input','id'=>'exampleInputEmail1','placeholder'=>'سعر الغسيل والكى'])!!}
        </div>

    </div>

    <div class="form-group m-form__group">
        <label for="exampleInputEmail1">الصوره</label>
        {!! Form::file('image',['class'=>'form-control '])!!}
    </div>

</div>
@push('scripts')

@endpush

resources/views/admin/categories/_table.blade.php
<!--begin: Datatable -->
<table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
    <thead>
    <tr>
{{--
        'name_ar', 'name_en', 'image', 'type', 'clean_price', 'dry_clean_price', 'clean_ironing_price', 'fast_clean_price', 'fast_dry_clean_price', 'fast_clean_ironing_price'--}}
        <th>التسلسل</th>
        <th>الصوره</th>
        <th>الاسم بالعربيه</th>
        <th>الاسم بالانجليزيه</th>
        <th>النوع</th>
        <th>سعر الغسيل</th>
        <th>سعر الغسيل والمكوى</th>
        <th>سعر الغسيل الجاف</th>
        <th>سعر الغسيل السريع</th>
        <th>سعر الغسيل والمكوى السريع</th>
        <th>سعر الغسيل الجاف السريع</th>

        <th>الاعدادت</th>
    </tr>
    </thead>
    <tbody>
    @foreach($categories as $category)
        <tr>
            <td>{!!$loop->iteration!!}</td>
           
            <td> <img src="{!! asset($category->image) !!}" width="100" height="100" alt="{!! $category->name !!}"></td>
            <td>{!!$category->name_ar!!}</td>
            <td>{!!$category->name_en!!}</td>
            <td>{!!$category->type!!}</td>
            <td>{!!$category->clean_price!!}</td>
            <td>{!!$category->dry_clean_price!!}</td>
            <td>{!!$category->clean_ironing_price!!}</td>
            <td>{!!$category->fast_clean_price!!}</td>
            <td>{!!$category->fast_dry_clean_price!!}</td>
            <td>{!!$category->fast_clean_ironing_price!!}</td>

            <td>
                <a href="{!!route('categories.edit',$category->id)!!}" class="btn btn-primary">
                    <i class="fas fa-pen"></i>
                    تعديل
                </a>

                <form method="POST" action="{!!route('categories.destroy',$category->id)!!}">
                    @csrf()
                     @method('delete')
                    <button type="submit" class="btn btn-danger">
                        <i class="fas fa-trash"></i>
                        حذف
                    </button>
                </form>
            </td>
        </tr>


    @endforeach

    </tbody>

</table>

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('title') اضافه قسم@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['الاقسام'=>route('categories.index'),'اضافه'=>route('categories.create')])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')


<div class="m-content">
    <div class="row">
        <div class="col-md-12">

            <!--begin::Portlet-->
            <div class="m-portlet m-portlet--tab">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                اضافه قسم
                            </h3>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->

                {!! Form::open(['method'=>'post','route'=>'categories.store','files'=>'true','class'=>'m-form m-form--fit
                m-form--label-align-right'])!!}
                @include('admin.categories._form')

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </div>
                </div>

                {!!Form::close()!!}
                <!--end::Form-->
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')
@section('title') تعديل بيانات {!!$category->name!!}@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['الاقسام'=>route('categories.index'),'تعديل'=>route('categories.edit',$category->id)])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')


<div class="m-content">
    <div class="row">
        <div class="col-md-12">

            <!--begin::Portlet-->
            <div class="m-portlet m-portlet--tab">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon m--hide">
                                <i class="la la-gear"></i>
                            </span>
                            <h3 class="m-portlet__head-text">
                                 تعديل   {!! $category->name_ar!!}
                            </h3>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->

                {!! Form::model($category,['method'=>'put','route'=>['categories.update',$category->id],'files'=>'true','class'=>'m-form m-form--fit
                m-form--label-align-right'])!!}
                @include('admin.categories._form')

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </div>
                </div>
                {!!Form::close()!!}
                <!--end::Form-->
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('title') الاقسام@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['الاقسام'=>route('categories.index'),])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')

 <div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    كل الاقسام
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{!!route('categories.create')!!}" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air">
                        <span>
                            <i class="la la-cart-plus"></i>
                            <span>اضافه </span>
                        </span>
                    </a>
                </li>
                <li class="m-portlet__nav-item"></li>

            </ul>
        </div>
    </div>
    <div class="m-portlet__body">

     @include('admin.categories._table')
    </div>
</div>

 @endsection
@section('scripts')@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layouts.app')
@section('title')@endsection
@section('header')@endsection
@section('breadcrumb')
@php($breadcrumbs=['الاعضاء'=>'/users','اضافه'=>'/users/create'])
@includeWhen(isset($breadcrumbs),'admin.layouts._breadcrumb', ['breadcrumbs' =>$breadcrumbs ])
@endsection
@section('content')@endsection
@section('scripts')@endsection